
stages:
  - build
  - release

build polkawatch packages:
  stage: build
  image: node:14-alpine
  script:
    - yarn install
    - yarn lint:test
    - yarn test
    - yarn test:e2e
    - yarn build

polkawatch docker release:
  stage: release
  image: docker:stable
  before_script:
    # Setup Git for Push
    - apk add --no-cache openssh-client git
    - mkdir ${HOME}/.ssh
    - echo "${CI_ROBOT_SSH_KEY_B64Z}" | base64 -d | gunzip > ${HOME}/.ssh/id_rsa
    # Login in docker repo
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    # Increase the version
    - yarn version --patch --message "[skip-ci] New Release %s"
    # Build the Docker Containers

    # Push the new version wihtout triggering CI
    - git push --tags

  when: manual
  only:
    - main
    - /^stable.*$/
