
stages:
  - build
  - release
  - deploy

build polkawatch packages:
  stage: build
  image: node:14-alpine
  services:
    - docker:19.03.12-dind
  before_script:
    # Setup Git for Push
    - apk add --no-cache docker-cli
  script:
    - yarn install
    - yarn lint:test
    - yarn build:client
    - yarn test
    - yarn test:e2e
    # In our context Build works more like "pack"
    - yarn build

polkawatch release:
  stage: release
  image: node:14-alpine
  before_script:
    # Setup Git for Push
    - apk add --no-cache openssh-client git
    - mkdir ${HOME}/.ssh
    - echo "${CI_ROBOT_SSH_KEY_B64Z}" | base64 -d | gunzip > ${HOME}/.ssh/id_rsa
    - chmod 600 ${HOME}/.ssh/id_rsa
    - ssh-keyscan gitlab.com >> ${HOME}/.ssh/known_hosts
    - git config --global user.email ${CI_ROBOT_EMAIL}
    - git config --global user.name "CI Robot"
    - git remote add porigin ssh://git@gitlab.com/${CI_PROJECT_PATH}.git
  script:
    # Increase the release number
    - yarn version --patch --message "[skip-ci] New Release %s"
    # Set workspace packages to the same version
    - APP_VERSION=$(yarn -s pkg:version)
    - yarn release:setversion ${APP_VERSION}
    - git commit packages -m "[skip-ci] Released workspace packages version ${APP_VERSION}"
    # Push to the branch the triggered
    - git push porigin HEAD:${CI_COMMIT_REF_NAME} --tags
    # Pass the version to the next stage
    - echo ${APP_VERSION} > .APP_VERSION
  when: manual
  allow_failure: false
  only:
    - main
    - /^stable.*$/
  artifacts:
    paths:
      - .APP_VERSION

polkawatch docker image deployment:
  stage: deploy
  dependencies:
    - polkawatch release
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    # Login in docker repo
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # Get the version from the artifacts
    - APP_VERSION=$(cat .APP_VERSION)
    # Build the Docker Containers, lock the individual packages
    - >
      for PACKAGE in archive indexer lqs; do
        cp yarn.lock packages/${PACKAGE}; 
        docker build -t $CI_REGISTRY/valletech/polkawatch-${PACKAGE}:latest -t $CI_REGISTRY/valletech/polkawatch-${PACKAGE}:${APP_VERSION} packages/${PACKAGE};
      done
    # Push the docker containers to the registry
    - >
      for PACKAGE in archive indexer lqs; do
        docker push $CI_REGISTRY/valletech/polkawatch-${PACKAGE}:latest;
        docker push $CI_REGISTRY/valletech/polkawatch-${PACKAGE}:${APP_VERSION}
      done
  only:
    - main
    - /^stable.*$/
